<div class="contact">
    <div class="row">
        <div class="col-xs-12 col-sm-6 hidden-xs">
            <div class="contact-title">
                <h3>PLEASE DO GET IN TOUCH!</h3>
            </div>
            <div class="contact-address-block">
                <div class="contact-address">
                    <div class="media">
                        <div class="media-body">
                            Please feel free to contact us by email, regular mail, or phone.
                        </div>
                    </div>
                </div>
                <div class="contact-contactinfo">
                    <div class="media">
                        <div class="media-body contact-telephone">
                            Address: 8th Meraguza St.(the Flea Market) Tel Aviv - Jaffa
                        </div>
                    </div>
                    <div class="media">
                        <div class="media-body contact-mobile">
                            <p class="s-phone">Phone: 00972.3.6041405</p>
                        </div>
                    </div>
                    <div class="media">
                        <div class="media-body contact-emailto">
                            <p><a href="mailto:stores@company.com">Email: shop@asufadesign.com</a></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xs-12 col-sm-6" id="wholesale-form-container" data-bind="scope: 'wholesaleForm'">
            <h3>Write Us</h3>
            <div class="page messages" style="display: none;">
                <div>
                    <div class="messages">
                        <div class="message">
                            <div></div>
                        </div>
                    </div>
                </div>
            </div>
            <form class="contact-form"
                    action="<?php /* @escapeNotVerified */ print $block->getFormAction(); ?>"
                    id="form-wholesale"
                    data-bind="submit: submitWholesaleForm"
                    method="post"
                    data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
                    data-mage-init='{"validation":{}}'>
                <p><div class="field note no-label">Jot us a note and we’ll get back to you as quickly as possible.</div></p>
                <p><input name="name" id="name" title="<?php /* @escapeNotVerified */ echo __('Full Name') ?>" placeholder="<?php /* @escapeNotVerified */ echo __('Full Name') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}"/></p>
                <p><input name="email" id="email" title="<?php /* @escapeNotVerified */ echo __('Email Address') ?>" placeholder="<?php /* @escapeNotVerified */ echo __('Email Address') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/></p>
                <p><input name="company" id="company" title="<?php /* @escapeNotVerified */ echo __('Company') ?>" placeholder="<?php /* @escapeNotVerified */ echo __('Company') ?>" value="" class="input-text" type="text"/></p>
                <p><input name="phone" id="phone" title="<?php /* @escapeNotVerified */ echo __('Phone Number') ?>" placeholder="<?php /* @escapeNotVerified */ echo __('Phone Number') ?>" value="" class="input-text" type="text" /></p
                <p><textarea name="comment" id="comment" title="<?php /* @escapeNotVerified */ echo __('Message') ?>" placeholder="<?php /* @escapeNotVerified */ echo __('Message') ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}"></textarea></p>
                <div class="form-actions">
                    <input type="hidden" name="hideit" id="hideit" value="" />
                    <button type="submit" title="<?php /* @escapeNotVerified */ echo __('send message') ?>" class="btn-novetty btn-raised primary">
                         <span><?php /* @escapeNotVerified */ echo __('send message') ?></span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "wholesaleForm": {
                    "component": "Eleanorsoft_Wholesale/js/wholesale"
                }
            }
        }
    }
}
</script>