
<div class="contact" data-bind="scope: 'contactForm'">
   <div class="row">
      <div class="col-xs-12">
        <div class="contact-maps"><iframe style="border: 0px; width: 100%;" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3724.5133253018125!2d105.80814449999995!3d21.01213699999998!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3135ab602de9caab%3A0x2defdd20ba3f2eac!2zMTY5IE5ndXnhu4VuIE5n4buNYyBWxaksIFRydW5nIEhvw6AsIEPhuqd1IEdp4bqleQ!5e0!3m2!1svi!2s!4v1395192834951" height="450" frameborder="0"></iframe></div>
      </div>
   </div>
   <div class="row">
      <div class="col-xs-12 col-sm-6 hidden-xs">
         <div class="contact-title">
                <h3>PLEASE DO GET IN TOUCH!</h3>
         </div>
         <div class="contact-address-block">
            <div class="contact-address">
               <div class="media">
                  <div class="media-body">
                      Please feel free to contact us by email, regular mail, or phone.
                  </div>
               </div>
            </div>
            <div class="contact-contactinfo">
               <div class="media">
                  <div class="media-body contact-telephone">
                      Address: 8th Meraguza St.(the Flea Market) Tel Aviv - Jaffa
                  </div>
               </div>
               <div class="media">
                  <div class="media-body contact-mobile">
                    <p class="s-phone">Phone: 00972.3.6041405</p>
                  </div>
               </div>
               <div class="media">
                  <div class="media-body contact-emailto">
                     <p><a href="mailto:stores@company.com">Email: shop@asufadesign.com</a></p>
                  </div>
               </div>
            </div>
         </div>
      </div>
      <div class="col-xs-12 col-sm-6 ">
         <h3>DROP US A LINE</h3>

          <div class="page messages" style="display: none;">
              <div>
                  <div class="messages">
                      <div class="message">
                          <div></div>
                      </div>
                  </div>
              </div>
          </div>

         <form class="contact-form"
          action="<?php /* @escapeNotVerified */ echo $block->getFormAction(); ?>"
          id="contact-form"
          method="post"
           data-bind="submit: submitContactForm"
          data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
          data-mage-init='{"validation":{}}'>

             <p><input name="name" id="name" title="<?php /* @escapeNotVerified */ echo __('Your name') ?>" placeholder="<?php /* @escapeNotVerified */ echo __('Your name') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}"/></p>
             <p><input name="email" id="email" title="<?php /* @escapeNotVerified */ echo __('Your email') ?>" placeholder="<?php /* @escapeNotVerified */ echo __('Your email') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/></p>
             <p><input name="subject" id="subject" title="<?php /* @escapeNotVerified */ echo __('Message Subject') ?>" placeholder="<?php /* @escapeNotVerified */ echo __('Message Subject') ?>" value="" class="input-text" type="text" data-validate="{required:true}"/></p>
             <p><input name="order" id="order" title="<?php /* @escapeNotVerified */ echo __('Order Number') ?>" placeholder="<?php /* @escapeNotVerified */ echo __('Order Number') ?>" value="" class="input-text" type="text"/></p>
             <input name="telephone" id="telephone" title="<?php /* @escapeNotVerified */ echo __('Phone Number') ?>" placeholder="<?php /* @escapeNotVerified */ echo __('Phone Number') ?>" value="" class="input-text" type="text" /></p
             <p><textarea name="comment" id="comment" title="<?php /* @escapeNotVerified */ echo __('Comments') ?>" placeholder="<?php /* @escapeNotVerified */ echo __('Comments') ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}"></textarea></p>

            <?php echo $block->getChildHtml('form.additional.info'); ?>
            <div class="form-actions">
               <input type="hidden" name="hideit" id="hideit" value="" />
                <button type="submit" title="<?php /* @escapeNotVerified */ echo __('send message') ?>" class="btn-novetty btn-raised primary">
                    <span><?php /* @escapeNotVerified */ echo __('send message') ?></span>
                </button>
            </div>
         </form>
      </div>
   </div>
</div>
<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "contactForm": {
                    "component": "Eleanorsoft_Contact/js/contact",
                    "beforeSend": "function () { return true; }",
                    "onSendError": "function () { return true; }",
                    "onSendSuccess": "function () { return true; }"
                }
            }
        }
    }
}
</script>
