<?php
/**
 * @category    CleverSoft
 * @package     CleverProduct
 * @copyright   Copyright © 2017 CleverSoft., JSC. All Rights Reserved.
 * @author        ZooExtension.com
 * @email       magento.cleversoft@gmail.com
 */

use Magento\Framework\App\Action\Action;

/* @var $this CleverSoft CleverProduct_Block_Widget */

$theme = $this->helper('CleverSoft\Base\Helper\Data');
$_id = $block->getConfig('id') ? $block->getConfig('id') : $block->getData('id');
$full_w = $block->getConfig('enable_fullwidth') ? $block->getConfig('enable_fullwidth') : $block->getData('enable_fullwidth');
$rtl_language = $theme->getCfg('responsive/rtl_language');
$_title = $block->getData('widget_title') ? $block->getData('widget_title') : $block->getConfig('widget_title');
$_sub_title = $block->getData('widget_sub_title') ? $block->getData('widget_sub_title') : $block->getConfig('widget_sub_title');
$t = microtime();
$tab = $block->getData('tab');
//Get icon lazy load
if ($theme->getCfg('category_grid/equal_height')) {
    $equalHeight = 'true';
} else $equalHeight = 'false';

$lazyload = $block->getData('lazyload');
if (is_null($lazyload)) $lazyload = false;
$min_height_img_lazyload = $block->getData('height_image');
//End get Icon lazy load
$icon = $theme->getCfg('responsive/iconlazyload');
if (!empty($icon)) {
    $image = $icon;
    $om = \Magento\Framework\App\ObjectManager::getInstance();
    $storeManager = $om->create('Magento\Store\Model\StoreManagerInterface');
    $image_url = $storeManager->getStore()
            ->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA) . 'lazyload/' . $image;
} else {
    $image_url = $block->getViewFileUrl('CleverSoft_Base::images/transparent.gif');
}
?>
<div class="<?php echo $block->getData('classes') ?> zoo-product-collection01" id="<?php echo $_id ?>">
    <?php if ($_title || $_sub_title): ?>
        <div class="zoo-main-heading">
            <?php if ($_title) : ?>
                <div class="zoo-heading-wrapper-title">
                    <h3><span><?php echo $_title ?></span></h3>
                    <?php if ($_sub_title): ?>
                        <p class="sub-title"><?php echo $_sub_title ?></p>
                    <?php endif; ?>
                </div>
            <?php endif; ?>
        </div>
    <?php endif ?>
    <?php if ($exist = ($block->getData('collection') && count($block->getData('collection')))): ?>
        <?php
        $type = 'widget-product-grid';

        $viewMode = 'grid';

        $count = $block->getData('collection') ? count($block->getData('collection')) : 0;
        $carousel = 1;
//
        $row = 1;
        $column = $carousel == 1 && $row == 1 ? $count : ($carousel == 1 && $row > 1 ? $row : $block->getData('column'));

        $image = 'new_products_content_widget_grid';
        $items = $block->getData('collection');

        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
        $description = false;
        $_imageHelper = $this->helper('CleverSoft\Base\Helper\Image');
        $_helper = $this->helper('Magento\Catalog\Helper\Output');


        $imgWidth = $block->getData('image_width');
        $imgHeight = $block->getData('image_height');

        // new config
        $showWishlist = $block->getData('display_addtowishlist');
        $showCompare = $block->getData('display_addtocompare');
        $showCart = $block->getData('display_addtocart');
        $showSwatchAttributes = $block->getData('display_swatch_attributes');
        $showPrice = $block->getData('display_price');
        $showRating = $block->getData('display_rating');
        $showProductName = $block->getData('display_productname');
        $nameInSingleLine = $block->getData('display_name_single_line');
        $product_grid_style = $block->getData('product_grid_style');
        $containerClasses = "{$viewMode} products-{$viewMode} products-grid-partitioned category-products-grid";
        $itemgridClasses = 'itemgrid zoo-itemgrid-adaptive';

        if ($nameInSingleLine)
            $containerClasses .= ' zoo-single-line-name';
        if ($theme->getCfg('category_grid/centered'))
            $containerClasses .= ' centered';
        if ($theme->getCfg('category_grid/enable_border_boxshadow'))
            $containerClasses .= ' enable_border_boxshadow';
        if ($theme->getCfg('category_grid/disable_border_radius'))
            $containerClasses .= ' disable_border_radius';

        //Image aspect ratio settings
        $keepAspectRatio = $block->getData('aspect_ratio');
        if (is_null($keepAspectRatio)) $keepAspectRatio = false;
        if ($keepAspectRatio) {
            $imgHeight = 0; //Height will be calculated automatically (based on width) to keep the aspect ratio
            $catViewKeepFrame = FALSE;
        } else {
            $catViewKeepFrame = TRUE;
        }
        ?>
        <div class="block widget zoo-block-products-list <?php echo $product_grid_style; ?> <?php /* @escapeNotVerified */ echo $viewMode; ?>">
            <div class="block-content">
                <?php $i = 0;
                foreach ($items as $_item): ?>
                    <?php if ($carousel == 1 && $row > 1 && $i == 0): ?>
                        <div class="owl-carousel">
                    <?php endif ?>
                    <?php /* @escapeNotVerified */
                    echo '<!-- ' . $image . '-->' ?>
                    <?php if ($i % $column == 0 || ($row > 1 && $i % $row == 0)): ?>
                    <div class="<?php /* @escapeNotVerified */
                    echo $containerClasses; ?>">
                    <ol class="<?php if($equalHeight == 'true') echo 'trigger-equal-height'; ?> product-items  <?php /* @escapeNotVerified */
                    echo $type; ?> <?php if ($itemgridClasses) echo $itemgridClasses; ?> <?php echo $carousel && $row == 1 ? ' owl-carousel' : '' ?>">
                <?php endif ?>
                    <?php $i++ ?>
                    <?php /* @escapeNotVerified */
                    $product_stock = 'product-instock';
                    echo ($i == 1) ? '<li class="product_hover ' . $product_stock . '">' : '</li><li class="product_hover ' . $product_stock . '">';

                    ?>
                    <div  class="product-item-info <?php if ($alternative_img = $_item['altImage']): ?> have-alternative-image <?php endif; ?>">
                        <div class="zoo-inner-product-item-info">
                            <div class="zoo-product-image">
                                <a href="<?php /* @escapeNotVerified */
                                echo $block->escapeHtml($_item['linkto']); ?>"
                                   class="product-item-photo" <?php if ($lazyload) echo 'style="min-height: ' . $min_height_img_lazyload . 'px"' ?> >

                                    <?php if (!$imgWidth) : ?>
                                        <img id="product-collection-image-<?php echo $_item['id']; ?>"
                                             data-src="<?php echo $block->escapeHtml($_item['image']); ?>"
                                             src="<?php echo (!$lazyload) ? $block->escapeHtml($_item['image']) : $image_url; ?>"
                                             class="<?php if ($lazyload) echo "clazyload"; ?> product-image-photo" width="auto" height="auto"
                                             alt="<?php echo $block->stripTags($_item['label'], null, true) ?>"/>
                                    <?php else: ?>
                                        <img id="product-collection-image-<?php echo $_item['id']; ?>"
                                             data-src="<?php echo $block->escapeHtml($_item['image']); ?>"
                                             src="<?php echo (!$lazyload) ? $block->escapeHtml($_item['image']) : $image_url; ?>"
                                             class="<?php if ($lazyload) echo "clazyload"; ?> product-image-photo" width="auto" height="auto"
                                             alt="<?php echo $block->stripTags($_item['label'], null, true) ?>"/>
                                    <?php endif; ?>
                                    <?php if ($theme->getCfg('category/alt_image')): ?>
                                        <span class="product-img-additional alt-image">
                                            <img src="<?php echo $alternative_img; ?>" alt="" />
                                         </span>
                                    <?php endif; ?>
                                </a>
                            </div>
                            <div class="product details product-item-details">
                                <div class="hover-area product_shop_loop">
                                    <?php if ($showProductName != 'remove'): ?>
                                        <h5 class="product-item-name ">
                                            <a title="<?php echo $block->escapeHtml($_item['label']) ?>"
                                               href="<?php /* @escapeNotVerified */
                                               echo $block->escapeHtml($_item['linkto']) ?>"
                                               class="product-item-link">
                                                <?php echo $block->escapeHtml($_item['label']) ?>
                                            </a>
                                        </h5>
                                    <?php endif; ?>
                                </div>

                            </div>
                        </div>
                    </div>
                    <?php echo ($i == count($items)) ? '</li>' : '' ?>
                    <?php if ($i == $count || $i % $column == 0 || ($row > 1 && $i % $row == 0)): ?>
                    </ol>
                    </div>
                <?php endif ?>
                    <?php if ($carousel == 1 && $row > 1 && $i == $count): ?>
                        </div>
                    <?php endif ?>
                <?php endforeach ?>
            </div>
        </div>
    <?php endif; ?>

</div>
<?php
?>
<script>
    require([
        "jquery",
        "cleverProductMage"
    ], function ($, cleverProductMage) {
        $(function () {
            <?php if($full_w) { ?>
            var $left = $('#<?php echo $_id; ?>').offset().left;
            $('#<?php echo $_id; ?>').css({
                'left': '-' + $left + 'px',
                'position': 'relative',
                'width': $(window).width() + 'px'
            });
            <?php if($rtl_language) : ?>
            $('#<?php  echo $_id;  ?>').css({'left': '0', 'right': '-' + $left + 'px'});
            <?php else : ?>
            $('#<?php  echo $_id;  ?>').css({'right': '0', 'left': '-' + $left + 'px'});
            <?php endif; ?>
            <?php } ?>
            $('#<?php echo $_id ?>').cleverProductMage({
                animation: <?php echo $block->getData('animation') ?>,
                parallax: <?php echo $block->getData('parallax') ?>,
                carousel: <?php echo $block->getData('carousel') ?>,
                carouselConfig: {
                },
                equalHeight: <?php  echo $equalHeight ; ?>,
                lazyload:<?php echo $lazyload ? 'true' : 'false'; ?>,
                countdown: <?php echo $block->getData('countdown') ?>,
                countdownConfig: {
                    dayText: '',
                    hourText: '',
                    minText: '',
                    secText: '',
                    daySingularText: '',
                    hourSingularText: '',
                    minSingularText: '',
                    secSingularText: ''
                },
                countdownTemplate: '<div class="day"><span class="no">%d</span><span class="text">days</span></div><div class="hours"><span class="no">%h</span><span class="text">hours</span></div><div class="min"><span class="no">%i</span><span class="text">Min</span></div><div class="second"><span class="no">%s</span><span class="text">Sec</span></div>',
            });
        });
    });
</script>


